[[rulesets]]
group = "🎯 全球直连"
ruleset = "rules/LocalAreaNetwork.list"

[[rulesets]]
group = "Ⓜ️ 微软服务"
ruleset = "rules/MSServices.list"

[[rulesets]]
group = "🎯 全球直连"

[[rulesets]]
group = "🛑 全球拦截"

[[rulesets]]
group = "🛑 全球拦截"

[[rulesets]]
group = "🎥 NETFLIX"

[[rulesets]]
group = "🌍 国外媒体"

[[rulesets]]
group = "🌏 国内媒体"

[[rulesets]]
group = "🌏 国内媒体"

[[rulesets]]
group = "🌏 国内媒体"

[[rulesets]]
group = "🌏 国内媒体"

[[rulesets]]
group = "🌏 国内媒体"

[[rulesets]]
group = "🌏 国内媒体"

[[rulesets]]
group = "📲 电报信息"

[[rulesets]]
group = "🔰 节点选择"

[[rulesets]]
group = "🍎 苹果服务"

[[rulesets]]
group = "🎯 全球直连"

[[rulesets]]
group = "🎯 全球直连"

[[rulesets]]
group = "🎯 全球直连"
ruleset = "[]GEOIP,CN"

[[rulesets]]
group = "🐟 漏网之鱼"
ruleset = "[]FINAL"

